name: Containers cleaner

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:

    - uses: socialgouv/actions/containers-cleaner@containers-cleaner
      with:
        organization: socialgouv
        token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
        retention-weeks: '2'
        containers: |
          fabrique/standup
          fabrique/carnets
          fabrique/hasura
          fabrique/www
          docker/no-k8s
