name: Containers cleaner

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:

    - uses: socialgouv/actions/containers-list@v1
      id: list
      with:
        organization: socialgouv

    - name: debug
      run: |
        echo "${{ steps.list.outputs.containers }}"

    - uses: socialgouv/actions/containers-cleaner@v1
      with:
        organization: socialgouv
        token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
        retention-weeks: '2'
        protected-tags: |
          ^main$
          ^master$
          ^dev$
          ^prod$
          ^latest$
          ^preprod$
          ^prod-(\w+)$
          ^(\d+\.\d+)(\.\d+)?(-(alpha|beta).\d+)?$
        containers: |
          ${{ steps.list.outputs.containers }}
